#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh

config_load multiwan
config_get enabled config enabled "1"
local ippassthrough=$(uci get lte.connect.ippassthrough)

case "${ACTION:-ifup}" in
	ifup)
		[ "$ippassthrough" = "Ethernet" ] || [ "$enabled" = "1" ] && /etc/init.d/multiwan restart 
	;;
	ifdown)
		#[ "$enabled" = "1" ] && /etc/init.d/multiwan restart
                [ "$ippassthrough" = "Ethernet" ] || [ "$enabled" = "1" ] && ip route flush cache 
	;;
esac
 
