#include "database.h"

#define LOGOPTS (LOG_PERROR|LOG_PID|LOG_LPR|LOG_ERR)  



/**********************************************************************************
   Function:     int main(int argc, char *argv[])
   Input:        no input
   Output:       no output
   Return:       0
   Note:         the main function of soip
**********************************************************************************/

#define LOG_WIDTH 1024
#define DBG_log soip_DBG_log
extern int soip_DBG_log(const char *message, ...);

#define COM_STATISTICS_RECEIVED_BYTES 0
#define COM_STATISTICS_RECEIVED_PACKETS 1     
#define COM_STATISTICS_RECEIVE_DROPED_BYTES 2
#define COM_STATISTICS_RECEIVE_DROPED_PACKETS 3     
#define COM_STATISTICS_SEND_BYTES 8
#define COM_STATISTICS_SEND_PACKETS 9
#define COM_STATISTICS_SENT_DROPED_BYTES 10
#define COM_STATISTICS_SENT_DROPED_PACKETS 11
#define COM_STATISTICS_PROGRAM_STATUS 19

#if defined(IXP425COM1) || defined(MPCI)	
    #define COM12 1
    #define SUB_MENU_COM12  				SUB_MENU_COM1
    #define COM12_ITEM_PORT_STATUS 			COM1_ITEM_PORT_STATUS
    #define COM12_ITEM_BAUD_RATE   			COM1_ITEM_BAUD_RATE
    #define COM12_ITEM_DATA_FORMAT			COM1_ITEM_DATA_FORMAT

    #define COM12_ITEM_DATA_MODE   			COM1_ITEM_DATA_MODE

    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM1_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MAXIMUM_PACKET_SIZE 	COM1_ITEM_MAXIMUM_PACKET_SIZE
    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM1_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MODBUS_MODE        COM1_ITEM_MODBUS_MODE
    #define COM12_ITEM_IP_PROTOCOL_CONFIG	COM1_ITEM_IP_PROTOCOL_CONFIG
    #define COM12_ITEM_NO_CONNECTION_DATA_INTAKE COM1_ITEM_NO_CONNECTION_DATA_INTAKE

    #define COM12_SUB_MENU_TCLIENT 			COM1_SUB_MENU_TCLIENT
    #define COM12_SUB_MENU_TSERVER			COM1_SUB_MENU_TSERVER
    #define COM12_SUB_MENU_TCLIENTSERVER	COM1_SUB_MENU_TCLIENTSERVER
    #define COM12_SUB_MENU_UPTOP 			COM1_SUB_MENU_UPTOP
    #define COM12_SUB_MENU_UPTOMP_AS_P		COM1_SUB_MENU_UPTOMP_AS_P
    #define COM12_SUB_MENU_UPTOMP_AS_MP 	COM1_SUB_MENU_UPTOMP_AS_MP
    #define COM12_SUB_MENU_UMPTOMP 			COM1_SUB_MENU_UMPTOMP

    #define COM12_MODBUS_CONF                    COM1_MODBUS_CONF
    #define COM12_MODBUS_ITEM_STATUS               COM1_MODBUS_ITEM_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_STATUS    COM1_MODBUS_ITEM_PROTECTION_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_KEY     COM1_MODBUS_ITEM_PROTECTION_KEY
    #define COM12_SUB_MENU_DATA_LOGGING     COM1_SUB_MENU_DATA_LOGGING
    
    #define COM12_SUB_MENU_SMTP             COM1_SUB_MENU_SMTP  
    #define COM12_SUB_MENU_SMS             COM1_SUB_MENU_SMS

#elif  defined(IXP425COM2) || defined(MPCI2)
    #define COM12 2
    #define SUB_MENU_COM12  				SUB_MENU_COM2
    #define COM12_ITEM_PORT_STATUS 			COM2_ITEM_PORT_STATUS
    #define COM12_ITEM_BAUD_RATE   			COM2_ITEM_BAUD_RATE
    #define COM12_ITEM_DATA_FORMAT			COM2_ITEM_DATA_FORMAT
    #define COM12_ITEM_DATA_MODE   			COM2_ITEM_DATA_MODE

    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM2_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MAXIMUM_PACKET_SIZE 	COM2_ITEM_MAXIMUM_PACKET_SIZE
    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM2_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MODBUS_MODE        COM2_ITEM_MODBUS_MODE
    #define COM12_ITEM_IP_PROTOCOL_CONFIG	COM2_ITEM_IP_PROTOCOL_CONFIG
    #define COM12_ITEM_NO_CONNECTION_DATA_INTAKE COM2_ITEM_NO_CONNECTION_DATA_INTAKE

    #define COM12_SUB_MENU_TCLIENT 	   		COM2_SUB_MENU_TCLIENT
    #define COM12_SUB_MENU_TSERVER			COM2_SUB_MENU_TSERVER
    #define COM12_SUB_MENU_TCLIENTSERVER	COM2_SUB_MENU_TCLIENTSERVER
    #define COM12_SUB_MENU_UPTOP 	  	    COM2_SUB_MENU_UPTOP
    #define COM12_SUB_MENU_UPTOMP_AS_P		COM2_SUB_MENU_UPTOMP_AS_P
    #define COM12_SUB_MENU_UPTOMP_AS_MP 	COM2_SUB_MENU_UPTOMP_AS_MP
    #define COM12_SUB_MENU_UMPTOMP 			COM2_SUB_MENU_UMPTOMP

    #define COM12_MODBUS_CONF                    COM2_MODBUS_CONF
    #define COM12_MODBUS_ITEM_STATUS               COM2_MODBUS_ITEM_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_STATUS    COM2_MODBUS_ITEM_PROTECTION_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_KEY     COM2_MODBUS_ITEM_PROTECTION_KEY
    #define COM12_SUB_MENU_DATA_LOGGING     COM2_SUB_MENU_DATA_LOGGING

    #define COM12_SUB_MENU_SMTP             COM2_SUB_MENU_SMTP
    #define COM12_SUB_MENU_SMS             COM2_SUB_MENU_SMS


#elif defined(IXP425USB)
    #define COM12 3
    #define SUB_MENU_COM12  				USB_SUB_MENU_DATA_MODE
    #define COM12_ITEM_PORT_STATUS 			USB_DATA_MODE_PORT_STATUS
    #define COM12_ITEM_BAUD_RATE   			USB_DATA_MODE_BAUD_RATE
    #define COM12_ITEM_DATA_FORMAT			USB_DATA_MODE_DATA_FORMAT
    #define COM12_ITEM_DATA_MODE   			USB_DATA_MODE_DATA_MODE

    #define COM12_ITEM_CHARACTER_TIMEOUT 	USB_DATA_MODE_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MAXIMUM_PACKET_SIZE 	USB_DATA_MODE_MAXIMUM_PACKET_SIZE
    #define COM12_ITEM_MODBUS_MODE          USB_DATA_MODE_MODBUS_MODE
    #define COM12_ITEM_IP_PROTOCOL_CONFIG	USB_DATA_MODE_IP_PROTOCOL_CONFIG
    #define COM12_ITEM_NO_CONNECTION_DATA_INTAKE USB_DATA_MODE_NO_CONNECTION_DATA_INTAKE

    #define COM12_SUB_MENU_TCLIENT 	   		USB_SUB_MENU_TCLIENT
    #define COM12_SUB_MENU_TSERVER			USB_SUB_MENU_TSERVER
    #define COM12_SUB_MENU_TCLIENTSERVER	USB_SUB_MENU_TCLIENTSERVER
    #define COM12_SUB_MENU_UPTOP 	  	    USB_SUB_MENU_UPTOP
    #define COM12_SUB_MENU_UPTOMP_AS_P		USB_SUB_MENU_UPTOMP_AS_P
    #define COM12_SUB_MENU_UPTOMP_AS_MP 	USB_SUB_MENU_UPTOMP_AS_MP
    #define COM12_SUB_MENU_UMPTOMP 			USB_SUB_MENU_UMPTOMP

    #define COM12_MODBUS_CONF                    USB_MODBUS_CONF
    #define COM12_MODBUS_ITEM_STATUS               USB_MODBUS_ITEM_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_STATUS    USB_MODBUS_ITEM_PROTECTION_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_KEY     USB_MODBUS_ITEM_PROTECTION_KEY

    #define COM12_SUB_MENU_SMTP             COM1_SUB_MENU_SMTP
    #define COM12_SUB_MENU_SMS             COM1_SUB_MENU_SMS

#else
    #define COM12 1
    #define SUB_MENU_COM12  				SUB_MENU_COM1
    #define COM12_ITEM_PORT_STATUS 			COM1_ITEM_PORT_STATUS
    #define COM12_ITEM_BAUD_RATE   			COM1_ITEM_BAUD_RATE
    #define COM12_ITEM_DATA_FORMAT			COM1_ITEM_DATA_FORMAT

    #define COM12_ITEM_DATA_MODE   			COM1_ITEM_DATA_MODE

    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM1_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MAXIMUM_PACKET_SIZE 	COM1_ITEM_MAXIMUM_PACKET_SIZE
    #define COM12_ITEM_CHARACTER_TIMEOUT 	COM1_ITEM_CHARACTER_TIMEOUT      
    #define COM12_ITEM_MODBUS_MODE        COM1_ITEM_MODBUS_MODE
    #define COM12_ITEM_IP_PROTOCOL_CONFIG	COM1_ITEM_IP_PROTOCOL_CONFIG
    #define COM12_ITEM_NO_CONNECTION_DATA_INTAKE COM1_ITEM_NO_CONNECTION_DATA_INTAKE

    #define COM12_SUB_MENU_TCLIENT 			COM1_SUB_MENU_TCLIENT
    #define COM12_SUB_MENU_TSERVER			COM1_SUB_MENU_TSERVER
    #define COM12_SUB_MENU_TCLIENTSERVER	COM1_SUB_MENU_TCLIENTSERVER
    #define COM12_SUB_MENU_UPTOP 			COM1_SUB_MENU_UPTOP
    #define COM12_SUB_MENU_UPTOMP_AS_P		COM1_SUB_MENU_UPTOMP_AS_P
    #define COM12_SUB_MENU_UPTOMP_AS_MP 	COM1_SUB_MENU_UPTOMP_AS_MP
    #define COM12_SUB_MENU_UMPTOMP 			COM1_SUB_MENU_UMPTOMP

    #define COM12_MODBUS_CONF                    COM1_MODBUS_CONF
    #define COM12_MODBUS_ITEM_STATUS               COM1_MODBUS_ITEM_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_STATUS    COM1_MODBUS_ITEM_PROTECTION_STATUS
    #define COM12_MODBUS_ITEM_PROTECTION_KEY     COM1_MODBUS_ITEM_PROTECTION_KEY
    
    #define COM12_SUB_MENU_SMTP             COM1_SUB_MENU_SMTP
    #define COM12_SUB_MENU_SMS             COM1_SUB_MENU_SMS  
#endif
