#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

restore_config() {
    [ -f /jffs/sysupgrade.tgz ] && {
	echo "- config restore -"
	#cd /jffs/
	mv /jffs/sysupgrade.tgz /tmp
	tar xzf /tmp/sysupgrade.tgz
	rm -f /tmp/sysupgrade.tgz
	#sync
    }
}

boot_hook_add preinit_main restore_config

