#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org


START=99
STOP=99

start(){

        killall -9 localmoncheck
        sleep 1
	config_load "localmonitor"
        config_get locmon_en localmon_conf LocalMon_Enable
    	if [ "${locmon_en}" = "B" ]; then
            /bin/localmoncheck &
            echo "local device monitor start."
	fi
}

stop(){
#       killall -9 localmonitor
       killall -9 localmoncheck
}

